### ISSUE TITLE
Can you provide a code for fairseq-video-captioning?

### ISSUE THREAD

**Issue by tuyunbin** [krasserm/fairseq-image-captioning#21]

**Comment by tuyunbin** [comment]
Hi, I am very interseted in your repo. Now, my research is video captioning, and I cannot find a good repo using transformer for video captioning baseline such as  “TVT: Two-View Transformer Network for Video Captioning”, so can you kindly provide a repro using transformer for this paper?

**Comment by krasserm** [comment]
Hi @tuyunbin, thanks for our interest in this repo. I currently don't plan to work on video captioning as there are still tasks left for this project and I also have to juggle with other priorities.
