### ISSUE TITLE
why loss is always 0.000 in epoch 1  ?

### ISSUE THREAD

**Issue by nvnhann** [krasserm/fairseq-image-captioning#33]
![image](https://user-images.githubusercontent.com/74455034/149972197-e2d9b2f2-ad9d-4ef9-b7ef-60e3a5542427.png)

**Comment by FantasyoO666** [comment]
> ![image](https://user-images.githubusercontent.com/74455034/149972197-e2d9b2f2-ad9d-4ef9-b7ef-60e3a5542427.png)

hi，i have the same question，please tell how you solve？

**Comment by FantasyoO666** [comment]
it is not zero，but +- wave, I want to know it is right ？because I'm new to reinforce learning
